name: LINEDart
description: "LINEDart is a library for control LINE."
version: 1.0.0
homepage: "https://github.com/hafusun/line.dart"

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fbthrift: ^1.0.0+4
  fixnum: ^1.1.1
  curve25519_vrf: ^2.0.1
  crypto: ^3.0.6
  encrypt: ^5.0.3
  pinenacl: ^0.6.0
  cryptography: ^2.7.0
  uuid: ^4.5.1
  http: ^1.4.0

  pointycastle: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0